name: Clone

on:
  workflow_dispatch:
    inputs:
      project:
        required: true
        type: string
        description: Name of the project to create
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Clone repository
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh repo create ${{ github.event.inputs.project }} --private --source=. --remote=upstream