name: Clone

on:
  workflow_dispatch:
    inputs:
      project:
        required: true
        type: string
        description: Name of the project to create
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create new repository
      env:
        GH_TOKEN: ${{ secrets.TOKEN }}
      run: gh repo create ${{ github.event.inputs.project }} --private
    - name: Push copy of project
      run: |
        git remote add upstream git@github.com:${{ github.repository_owner }}/${{ github.event.inputs.project }}.git
        git push upstream main