name: Clone

permissions: write-all

on:
  workflow_dispatch:
    inputs:
      project:
        required: true
        type: string
        description: Name of the project to create
jobs:
  build:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
    - name: Create new repository
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: | 
        gh repo create ${{ github.event.inputs.project }} --private
#    - name: Pushes to another repository
#      uses: cpina/github-action-push-to-another-repository@main
#      env:
#        API_TOKEN_GITHUB: ${{ secrets.GH_TOKEN }}
#      with:
#        source-directory: '.'
#        destination-github-username: ${{ github.repository_owner }}
#        destination-repository-name: ${{ github.event.inputs.project }}
#    - name: Push copy of project
#      env:
#        GH_TOKEN: ${{ secrets.GH_TOKEN }}
#      run: |
#        git remote remove origin
#        git remote add origin https://hekonsek:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository_owner }}/${{ github.event.inputs.project }}.git
#        git push -u origin main
    - name: Push copy of project
      run: |
        git remote add ups https://hekonsek:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository_owner }}/${{ github.event.inputs.project }}.git
        git push -u ups main 
 

### Token:
#  all repo
# all workflow
#  write:org