name: Create new project

on:
  workflow_dispatch:
    inputs:
      project:
        required: true
        type: string
        description: Name of the project to create

jobs:
  create-new-project:
    runs-on: ubuntu-latest

    steps:
      - uses: hekonsek/action-create-new-project@v0.3.0
        with:
          project: ${{ github.event.inputs.project }}
          token: ${{ secrets.GH_TOKEN }}